class Cars {
    _makes = [
        "ACURA",
        "ALFA ROMEO",
        "AMC",
        "ARIEL",
        "ASTON MARTIN",
        "AUDI",
        "AUSTIN HEALEY",
        "BENTLEY",
        "BMW",
        "BUGATTI",
        "BUICK",
        "CADILLAC",
        "CALLAWAY",
        "CATERHAM",
        "CHEVROLET",
        "CHRYSLER",
        "CITROEN",
        "DAEWOO",
        "DAIHATSU",
        "DATSUN",
        "DE TOMASO",
        "DODGE",
        "EAGLE",
        "FERRARI",
        "FIAT",
        "FISKER",
        "FORD",
        "GENESIS",
        "GEO",
        "GMC",
        "HOLDEN",
        "HONDA",
        "HUMMER",
        "HYUNDAI",
        "INFINITI",
        "ISUZU",
        "JAGUAR",
        "JEEP",
        "KIA",
        "KOENIGSEGG",
        "LAMBORGHINI",
        "LANCIA",
        "LAND ROVER",
        "LEXUS",
        "LINCOLN",
        "LOTUS",
        "MASERATI",
        "MAYBACH",
        "MAZDA",
        "MCLAREN",
        "MERCEDES",
        "MERCURY",
        "MG",
        "MINI",
        "MITSUBISHI",
        "MORGAN",
        "MOSLER / ROSSION",
        "NISSAN",
        "NOBLE",
        "OLDSMOBILE",
        "OPEL",
        "PAGANI",
        "PEUGEOT",
        "PLYMOUTH",
        "PONTIAC",
        "PORSCHE",
        "PROTON",
        "RAM",
        "RENAULT",
        "ROLLS-ROYCE",
        "SAAB",
        "SALEEN",
        "SATURN",
        "SCION",
        "SEAT",
        "SHELBY",
        "SKODA",
        "SMART",
        "SSANGYONG",
        "SUBARU",
        "SUZUKI",
        "TESLA",
        "TOYOTA",
        "TRIUMPH",
        "VAUXHALL",
        "VW",
        "VOLVO",
        "WESTFIELD",
    ]

    getCarMakes() {
        return this._makes
    }
}

export default Cars
